In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("titanic.csv")
df.head()

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0

In [3]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

   Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [4]:
inputs = df.drop('Survived',axis='columns')
target = df.Survived

In [5]:
#inputs.Sex = inputs.Sex.map({'male': 1, 'female': 2})

In [6]:
dummies = pd.get_dummies(inputs.Sex)
dummies.head(3)

   female   male
0   False   True
1    True  False
2    True  False

In [7]:
inputs = pd.concat([inputs,dummies],axis='columns')
inputs.head(3)

   Pclass     Sex   Age     Fare  female   male
0       3    male  22.0   7.2500   False   True
1       1  female  38.0  71.2833    True  False
2       3  female  26.0   7.9250    True  False

In [8]:
#I am dropping male column as well because of dummy variable trap theory. 
#One column is enough to repressent male vs female

In [9]:
inputs.drop(['Sex','male'],axis='columns',inplace=True)
inputs.head(3)

   Pclass   Age     Fare  female
0       3  22.0   7.2500   False
1       1  38.0  71.2833    True
2       3  26.0   7.9250    True

In [10]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [11]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [12]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head()

   Pclass   Age     Fare  female
0       3  22.0   7.2500   False
1       1  38.0  71.2833    True
2       3  26.0   7.9250    True
3       1  35.0  53.1000    True
4       3  35.0   8.0500   False

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs,target,test_size=0.3)

In [14]:
#Gaussian naive base we can use when our data set is simple

In [15]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [16]:
model.fit(X_train,y_train)

GaussianNB()

In [17]:
model.score(X_test,y_test)

0.7649253731343284

In [18]:
X_test[0:10]

     Pclass   Age     Fare  female
881       3  33.0   7.8958   False
764       3  16.0   7.7750   False
9         2  14.0  30.0708    True
688       3  18.0   7.7958   False
371       3  18.0   6.4958   False
510       3  29.0   7.7500   False
869       3   4.0  11.1333   False
114       3  17.0  14.4583    True
18        3  31.0  18.0000    True
122       2  32.5  30.0708   False

In [19]:
y_test[0:10]

881    0
764    0
9      1
688    0
371    0
510    1
869    1
114    0
18     0
122    0
Name: Survived, dtype: int64

In [20]:
model.predict(X_test[0:10])

array([0, 0, 1, 0, 0, 0, 0, 1, 1, 0])

In [21]:
#if you want see probality of above result then we need to call below function
model.predict_proba(X_test[:10])

array([[0.96693855, 0.03306145],
       [0.95808526, 0.04191474],
       [0.19592191, 0.80407809],
       [0.95977479, 0.04022521],
       [0.95932282, 0.04067718],
       [0.96580341, 0.03419659],
       [0.94353042, 0.05646958],
       [0.38622304, 0.61377696],
       [0.43484662, 0.56515338],
       [0.92541918, 0.07458082]])